#! /usr/bin/env python3

import pyrebrandly.api as api

import click

client = api.Client()


@click.group()
@click.option('-v', '--verbose', default=False)
@click.pass_context
def base(ctx, verbose):
    ctx.cfg['VERBOSE'] = verbose

@base.command()
@click.pass_context
def setup(ctx):
    print(ctx.cfg['VERBOSE'])

if __name__ == '__main__':
    base(cfg={})
